extraction:
  cpp:
    prepare:
      packages:
        - python3-cffi
        - python3-six
        - python3-yaml
        - python3-jsonschema
        - python3-docutils

path_classifiers:
  vendor:
    - "**/flux/utils/**/*.py"
