coverage:
 round: down
 range: "65...100"
 ignore:
 - "^t/.*"
 - ".*/test/.*"
 - ".*/tests/.*"
 - ".*/man3/.*"
 - ".*/common/libtap/.*"
 - ".*/common/liblsd/.*"
 - ".*/common/libev/.*"
 - ".*/common/libtomlc99/.*"
 - ".*/common/liboptparse/getopt*"
 - ".*/bindings/python/.*.c"
 - ".*/common/libminilzo/.*"
 - "/usr/include/.*"
 - "/usr/lib/.*"

 # Allow coverage to drop up to 0.1%
 status:
  project:
   default:
    threshold: .1

comment:
 layout: "header, diff, changes, tree"
 behavior: new
